### ISSUE TITLE
Using Relationship interface without data

### ISSUE THREAD

**Issue by scriptcoded** [rmarganti/json-api#2]
Hi,

Great work on these typings. I'm trying to use the `Relationship` interface without any type, but no matter what I try I can't have a `Relationship` with just `links`. `data` is always required. Also, [this line](https://github.com/rmarganti/json-api/blob/master/packages/ts-json-api/src/types/resourceObjects.ts#L69) doesn't seem to help, as it never goes to the `never` type.

Am I perhaps doing something wrong, or is the library not intended for this use case?

This piece of code:
```typescript
const rel: Relationship = {
  links: {
    self: '/users/1/relationships/decks',
    related: '/users/1/decks'
  }
}
```
gives the following error:
```
Property 'data' is missing in type '{ links: { self: string; related: string; }; }' but required in type 'Relationship<ResourceObject | ResourceObject[]>'.
```

Cheers,
Malcolm

**EDIT:**
This regards the `ts-json-api` package.

**Comment by rmarganti** [comment]
I'm reviewing the spec now:

> A “relationship object” MUST contain at least one of the following:
>
> - **links**: a links object containing at least one of the following:
> - **self**: a link for the relationship itself (a “relationship link”). This link allows the client to directly manipulate the relationship. For example, removing an author through an article’s relationship URL would disconnect the person from the article without deleting the people resource itself. When fetched successfully, this link returns the linkage for the related resources as its primary data. (See Fetching Relationships.)
> - **related**: a related resource link
> - **data**: resource linkage
> - **meta**: a meta object that contains non-standard meta-information about the relationship.

So, you are correct. This does appear to be an issue with my interface The `data` attribute should not be required.

**Comment by scriptcoded** [comment]
I was about to rip my hair of and do a hacky fork, so thank's for getting back so quickly. Is there anything I can help with?

**Comment by rmarganti** [comment]
I am always accepting PRs if you feel like giving it a go. Otherwise, I'll get it addressed in the next day or two.

**Comment by scriptcoded** [comment]
@rmarganti I'm sure you'll be able to have it figured out sooner than me. If you have the time, I think it'd be done better by you!

**Comment by rmarganti** [comment]
This has been addressed in an alpha version at `ts-json-api@next`. The final version of this fix may change slightly in the final version, because there are some other use cases I'd like to address. I am tracking that in the following, separate issue:

https://github.com/rmarganti/json-api/issues/3
