### ISSUE TITLE
Should Attribute values accept null as a type?

### ISSUE THREAD

**Issue by omnihound** [rmarganti/json-api#6]
I am using `ts-json-api` in a project where `null` is returned in a fast json api attribute value.  The application is currently throwing a type error because of this.

**Comment by rmarganti** [comment]
Yep, `null` is a valid JSON value and, therefore, should be supported in `Attributes`. I'll get this addressed.

**Comment by rmarganti** [comment]
Just published `ts-json-api@1.1.2`.
